#ifndef CONF_EVOLUTION__H_
#define CONF_EVOLUTION__H_

#define EVO_LEAF_SIZE	20.0f
#define EVO_MUTATION_ADD_ONEIN	(500 / 10)
#define EVO_MUTATION_RM_ONEIN	(100 / 10)
#define EVO_SUN_MOVEMENT_RADIUS	300.0f
#define EVO_UNITS_ON_GENERATION	10
#define EVO_INITIAL_NUM_BRANCHES 10

#endif
